name: bot

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  zig-update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.repository }}"
          ref: "${{ github.event.repository.default_branch }}"
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 'master'
      - name: Build
        shell: 'bash'
        run: zig build -freference-trace --verbose
