name: ci

on:
  pull_request:
    branches:
      - trunk

env:
  SHELL: "bash"
  ZIG_VERSION: "0.13.0"

jobs:
  build:
    strategy:
      matrix:
        repo:
          - vulkan
          - wayland
          - X11
          - glfw
          - cimgui
          - spirv
          - glslang
          - shaderc
          - oniguruma
          - libjq
    runs-on: ubuntu-latest
    steps:
    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.ZIG_VERSION }}

    - name: Install packages
      if: matrix.repo == 'cimgui'
      shell: ${{ env.SHELL }}
      run: |
        sudo apt-get install -y libwayland-bin python3-venv mesa-utils
        printf 'ACTIVATE_DIR=bin\n' >> "${GITHUB_ENV}"

    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"

    - name: Activate python virtual env & install pip packages
      if: matrix.repo == 'cimgui'
      env:
        RUNNER_TMP: "${{ runner.temp }}"
      shell: ${{ env.SHELL }}
      run: |
        python3 -m venv "${RUNNER_TMP}/venv"
        source "${RUNNER_TMP}/venv/${ACTIVATE_DIR:-Scripts}/activate"
        pip install ply

    - name: Prepare ${{ matrix.repo }}.zig/build.zig.zon
      env:
        SHA: "${{ github.event.pull_request.head.sha }}"
        URL: "${{ github.server_url }}/${{ github.repository }}/archive"
      shell: ${{ env.SHELL }}
      run: |
        old_url="$(grep -o "${URL}/.*\.tar\.gz" build.zig.zon)"
        old_hash="$(zig fetch "${old_url}")"
        new_url="${URL}/${SHA}.tar.gz"
        new_hash="$(zig fetch "${new_url}")"
        sed -i "s@${old_url}@${new_url}@;s@${old_hash}@${new_hash}@" build.zig.zon

    - name: Test updating ${{ matrix.repo }}.zig
      env:
        IS_CIMGUI: "${{ matrix.repo == 'cimgui' && 'true' || 'false' }}"
        RUNNER_TMP: "${{ runner.temp }}"
      shell: ${{ env.SHELL }}
      run:
        if [[ "${IS_CIMGUI}" == 'true' ]]
        then
          source "${RUNNER_TMP}/venv/${ACTIVATE_DIR:-Scripts}/activate"
          zig build -Dupdate '-Dplatform=GLFW -Drenderer=Vulkan'
        else
          zig build -Dupdate
        fi

    - name: Test fetching ${{ matrix.repo }}.zig
      env:
        IS_CIMGUI: "${{ matrix.repo == 'cimgui' && 'true' || 'false' }}"
        RUNNER_TMP: "${{ runner.temp }}"
      shell: ${{ env.SHELL }}
      run:
        if [[ "${IS_CIMGUI}" == 'true' ]]
        then
          source "${RUNNER_TMP}/venv/${ACTIVATE_DIR:-Scripts}/activate"
          zig build -Dfetch '-Dplatform=GLFW -Drenderer=Vulkan'
        else
          zig build -Dfetch
        fi
